/** Debounce do autosave do cadastro de imóveis (ms). */
export const IMOVEIS_AUTOSAVE_DEBOUNCE_MS = 700;

/** Snapshot estável dos campos persistidos — evita PUT redundante. */
export function buildSnapshotImovelCadastro(data) {
  const d = data ?? {};
  return JSON.stringify({
    imovelId: d.imovelId,
    imovelOcupado: !!d.imovelOcupado,
    codigo: String(d.codigo ?? ''),
    proc: String(d.proc ?? ''),
    observacoesInquilino: String(d.observacoesInquilino ?? ''),
    endereco: String(d.endereco ?? ''),
    municipioId: d.municipioId ?? null,
    condominio: String(d.condominio ?? ''),
    unidade: String(d.unidade ?? ''),
    garagens: String(d.garagens ?? ''),
    garantia: String(d.garantia ?? ''),
    valorGarantia: String(d.valorGarantia ?? ''),
    valorLocacao: String(d.valorLocacao ?? ''),
    taxaAdministracaoPercent: String(d.taxaAdministracaoPercent ?? ''),
    diaPagAluguel: String(d.diaPagAluguel ?? ''),
    formaPagamentoAluguel: String(d.formaPagamentoAluguel ?? ''),
    dataPag1TxCond: String(d.dataPag1TxCond ?? ''),
    inscricaoImobiliaria: String(d.inscricaoImobiliaria ?? ''),
    existeDebIptu: String(d.existeDebIptu ?? ''),
    dataConsIptu: String(d.dataConsIptu ?? ''),
    aguaNumero: String(d.aguaNumero ?? ''),
    dataConsAgua: String(d.dataConsAgua ?? ''),
    existeDebAgua: String(d.existeDebAgua ?? ''),
    diaVencAgua: String(d.diaVencAgua ?? ''),
    energiaNumero: String(d.energiaNumero ?? ''),
    dataConsEnergia: String(d.dataConsEnergia ?? ''),
    existeDebEnergia: String(d.existeDebEnergia ?? ''),
    diaVencEnergia: String(d.diaVencEnergia ?? ''),
    gasNumero: String(d.gasNumero ?? ''),
    dataConsGas: String(d.dataConsGas ?? ''),
    existeDebGas: String(d.existeDebGas ?? ''),
    diaVencGas: String(d.diaVencGas ?? ''),
    dataInicioContrato: String(d.dataInicioContrato ?? ''),
    dataFimContrato: String(d.dataFimContrato ?? ''),
    dataConsDebitoCond: String(d.dataConsDebitoCond ?? ''),
    existeDebitoCond: String(d.existeDebitoCond ?? ''),
    diaRepasse: String(d.diaRepasse ?? ''),
    banco: String(d.banco ?? ''),
    agencia: String(d.agencia ?? ''),
    numeroBanco: String(d.numeroBanco ?? ''),
    conta: String(d.conta ?? ''),
    cpfBanco: String(d.cpfBanco ?? ''),
    titular: String(d.titular ?? ''),
    chavePix: String(d.chavePix ?? ''),
    proprietarioNumeroPessoa: String(d.proprietarioNumeroPessoa ?? ''),
    proprietario: String(d.proprietario ?? ''),
    proprietarioCpf: String(d.proprietarioCpf ?? ''),
    proprietarioContato: String(d.proprietarioContato ?? ''),
    linkVistoria: String(d.linkVistoria ?? ''),
    inquilinoNumeroPessoa: String(d.inquilinoNumeroPessoa ?? ''),
    inquilino: String(d.inquilino ?? ''),
    inquilinoCpf: String(d.inquilinoCpf ?? ''),
    inquilinoContato: String(d.inquilinoContato ?? ''),
    inquilinos: d.inquilinos ?? [],
    fiadores: d.fiadores ?? [],
    infoIptuTexto: String(d.infoIptuTexto ?? ''),
    contratoAssinadoInquilino: String(d.contratoAssinadoInquilino ?? ''),
    contratoAssinadoProprietario: String(d.contratoAssinadoProprietario ?? ''),
    contratoAssinadoGarantidor: String(d.contratoAssinadoGarantidor ?? ''),
    contratoAssinadoTestemunhas: String(d.contratoAssinadoTestemunhas ?? ''),
    contratoArquivado: String(d.contratoArquivado ?? ''),
    contratoIntermediacaoArquivado: String(d.contratoIntermediacaoArquivado ?? ''),
    contratoIntermediacaoAssinadoProprietario: String(d.contratoIntermediacaoAssinadoProprietario ?? ''),
  });
}
