CREATE TABLE whatsapp_cobrancas (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    lote_id VARCHAR(36) NOT NULL,
    lote_descricao VARCHAR(255),
    pessoa_id BIGINT,
    cliente_id BIGINT,
    pessoa_nome VARCHAR(255),
    phone_number VARCHAR(20) NOT NULL,
    imovel_id BIGINT,
    condominio_nome VARCHAR(255),
    unidade_descricao VARCHAR(255),
    processo_id BIGINT,
    valor_pendente DECIMAL(15, 2),
    status VARCHAR(15) NOT NULL DEFAULT 'PENDENTE',
    wa_message_id VARCHAR(255),
    error_message VARCHAR(500),
    enviado_at TIMESTAMP NULL,
    created_by VARCHAR(100),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_cobranca_lote (lote_id),
    INDEX idx_cobranca_status (status),
    INDEX idx_cobranca_imovel (imovel_id),
    INDEX idx_cobranca_cliente (cliente_id),
    INDEX idx_cobranca_wa_msg (wa_message_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
