CREATE TABLE contrato_honorarios_importacao (
    id                      BIGINT NOT NULL AUTO_INCREMENT,
    importacao_lote_id      VARCHAR(36) NOT NULL,
    cliente_id              BIGINT NULL,
    codigo_cliente          CHAR(8) NULL,
    processo_id             BIGINT NULL,
    processo_stub_criado    TINYINT(1) NOT NULL DEFAULT 0,
    pessoa_id               BIGINT NULL,
    pdf_drive_file_id       VARCHAR(128) NULL,
    pdf_nome_arquivo        VARCHAR(255) NULL,
    hash_pdf                VARCHAR(64) NOT NULL,
    hash_pdf_ativo          VARCHAR(64) NULL,
    clausula_extraida_texto TEXT NULL,
    dados_extraidos_json    LONGTEXT NULL,
    dados_aprovados_json    LONGTEXT NULL,
    score_confianca         DECIMAL(5, 2) NULL,
    alertas_json            LONGTEXT NULL,
    roteamento_tipo         VARCHAR(20) NULL,
    status                  VARCHAR(20) NOT NULL,
    contrato_honorarios_id  BIGINT NULL,
    mensalista_id           BIGINT NULL,
    conciliacao_json        LONGTEXT NULL,
    criado_por_usuario_id   BIGINT NULL,
    criado_em               TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    atualizado_em           TIMESTAMP(6) NULL,
    aprovado_em             TIMESTAMP(6) NULL,
    revertido_em            TIMESTAMP(6) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_chi_hash_ativo (hash_pdf_ativo),
    KEY idx_chi_lote (importacao_lote_id),
    KEY idx_chi_status (status),
    KEY idx_chi_cliente (cliente_id),
    KEY idx_chi_processo (processo_id),
    KEY idx_chi_score (score_confianca DESC),
    KEY idx_chi_hash_pdf (hash_pdf),
    CONSTRAINT fk_chi_cliente FOREIGN KEY (cliente_id) REFERENCES cliente (id),
    CONSTRAINT fk_chi_processo FOREIGN KEY (processo_id) REFERENCES processo (id),
    CONSTRAINT fk_chi_pessoa FOREIGN KEY (pessoa_id) REFERENCES pessoa (id),
    CONSTRAINT fk_chi_contrato FOREIGN KEY (contrato_honorarios_id) REFERENCES contrato_honorarios (id),
    CONSTRAINT fk_chi_mensalista FOREIGN KEY (mensalista_id) REFERENCES mensalista (id),
    CONSTRAINT fk_chi_usuario FOREIGN KEY (criado_por_usuario_id) REFERENCES usuarios (id)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

ALTER TABLE processo
    ADD COLUMN importacao_item_id BIGINT NULL,
    ADD KEY idx_processo_importacao_item (importacao_item_id),
    ADD CONSTRAINT fk_processo_importacao_item
        FOREIGN KEY (importacao_item_id) REFERENCES contrato_honorarios_importacao (id);
